### ISSUE TITLE
Is it possible to merge multiple Ctxts into one?

### ISSUE THREAD

**Issue by NanXiao** [shaih/HElib#146]
Hi all,

I am just wondering if there is a method to merge multiple `Ctxt`s into one. For example:  

```
const EncryptedArray *ea = secretKey.getContext().ea;
long slots = ea->size();

Ctxt c1(pubKey);
vector<long> v1(slots / 2, 1);
ea->encrypt(c1, pubKey, v1);

Ctxt c2(pubKey);
vector<long> v2(slots / 2, 2);
ea->encrypt(c2, pubKey, v2);

Ctxt c3(pubKey);
```

From above code, we can see half of `c1 Ctxt` and `c2 Ctxt` are empty and `c1` and `c2` have available slots. Is it possible to merge `c1` and `c2` into one `Ctxt` which is full?

Thanks!

Best Regards
Nan Xiao

**Comment by ssmiler** [comment]
You can add them ;) if the 'empty' half has zeros.

Le 15 juin 2017 4:23 AM, "Nan Xiao" <notifications@github.com> a écrit :

Hi all,

I am just wondering if there is a method to merge multiple Ctxts into one.
For example:

const EncryptedArray *ea = secretKey.getContext().ea;
long slots = ea->size();

Ctxt c1(pubKey);
vector<long> v1(slots / 2, 1);
ea->encrypt(c1, pubKey, v1);

Ctxt c2(pubKey);
vector<long> v2(slots / 2, 2);
ea->encrypt(c2, pubKey, v2);

Ctxt c3(pubKey);

From above code, we can see half of c1 Ctxt and c2 Ctxt are empty and c1
and c2 have available slots. Is it possible to merge c1 and c2 into one Ctxt
which is full?

Thanks!

Best Regards
Nan Xiao

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shaih/HElib/issues/146>, or mute the thread

**Comment by NanXiao** [comment]
@ssmiler Per my understanding, if add `c1 + c2` directly, it will be "non-empty slot + non-empty slot" and "empty slot + empty slot". Is it correct? Thx!

**Comment by fionser** [comment]
@NanXiao @ssmiler 
I am not sure whether `EncryptedArrary::encrypt` can work, if only half of the slots are used.
Anyway, we can use some "0" entries.
For instance, assume we have 6 slots,  and for vector `a = [1, 2, 3]` we can encrypt `[1,2,3,0,0,0]`.
For the other vector 'b = [4,5,6]` we can encrypt with `[0,0,0,4,5,6]` (or encrypt with [4,5,6,0,0,0] and apply the rotation). Thus, the addition of E(a) + E(b) gives E([1,2,3,4,5,6]), somehow the merge of `a` and `b`.

**Comment by NanXiao** [comment]
@fionser Thanks for your comments! I will try it. BTW, your comment format is messy. Could you format again? Thanks! :-)
