### ISSUE TITLE
DoubleCRT Mulitplication without ModUp

### ISSUE THREAD

**Issue by fionser** [shaih/HElib#175]
Hi, I have a question about the ModUp operation in DoubleCRT's multiplication.

In the `FHESecKey::Encryption` method, we create a RLWE sample from the secret key.
From [Line 36 of FHE.cpp](https://github.com/shaih/HElib/blob/master/src/FHE.cpp#L36), the RLWE sample is created with the flag `matchIndexSets = false`. Indeed this multiplication is  `sk * c_1`.

 I am wondering that what is the difference between `matchIndexSets = true` and `false` ? In my understandings, `sk * c_1` is a multiplication of two polynomials (in the form of DoubleCRT).

**Comment by shaih** [comment]
See comment in [DoubleCRT.h, lines 82-85](https://github.com/shaih/HElib/blob/master/src/DoubleCRT.h#L82-L85):
```
  // The behavior when *this and other use different primes depends on the flag
  // matchIndexSets. When it is set to true then the effective modulus is
  // determined by the union of the two index sets; otherwise, the index set
  // of *this.
```
Recall that a DoubleCRT object is defined relative to some modulus. (Mathematically, such object represents the equivalent class of some polynomial P(X) in the quotient ring Z[X]/(Phi_m(X), q). Below I refer to the integer q as the modulus of that object.) 

Calling `c1.Mul(sk,...)` you indeed get the product `sk*c_1`. But in the case where `sk` and `c_1` are defined relative to two different moduli, the product will either be defined relative to the LCM of the two moduli (if `matchIndexSets=true`) or relative to the modulus of c1 (if `matchIndexSets=false`). Since we will then add the result to `c0` (that typically has the same modulus as `c1`), it saves a bit of time to use `matchIndexSets=false`.

**Comment by fionser** [comment]
Thanks @shaih ,
Actually, I am working on "encrypting sk", `Enc(sk[i])` for each element of `sk`. 
Then, I can homomorphically compute the `sk * c_1` (indeed, I only want the first coefficient of `sk * c_1`). 

But, I got the wrong answer. I figured out that in `RLWE` method, the `c_1 * sk` is done with `matchIndexs = false`. So should I consider `c_1 * sk` is under the prime moduli of `c_1`. 

Let the moduli of ciphertext be `p` and let the moduli of `sk` be `P`, so the `c_1 * sk` should be considered as `c_1 * sk \mod p` if `matchINdexSets = false` ?

**Comment by shaih** [comment]
I don't understand what you are trying to do. But note that when you do homomorphic computations, then the result will be modulo the plaintext-space parameter, not the ciphertext modulus. So whether or not you set `matchINdexSets=true` seems irrelevant here.

**Comment by fionser** [comment]
@shaih The basic problem I meet is that `[[m]_Q]]_q \neq [m]_q` where `Q` is the ciphertext modulus, and `q` is the plaintext modulus.
