### ISSUE TITLE
Ctxt::multByConstant( ) with NTL::ZZX.

### ISSUE THREAD

**Issue by fionser** [shaih/HElib#176]
Hi, I got an unexpected behavior of the `multByConstant` method. 
The problem occurs when I try to multiply a NTL::ZZX object (with a value larger than p^r) to the ciphertext. 

Here is the codes:
```
void test_mod_Q(FHESecKey const& sk, FHEPubKey const& pk) {
    FHEcontext const& context = pk.getContext();
    auto Q = context.productOfPrimes(context.ctxtPrimes);
    auto q = pk.getPtxtSpace();
    NTL::ZZ large_value = NTL::RandomBnd(Q);

    Ctxt ctxt(pk);
    long plain = NTL::RandomBnd(q);
    pk.Encrypt(ctxt, NTL::to_ZZX(plain));

    //auto poly = NTL::ZZX(NTL::rem(large_value, q)); // Works fine with small value
    auto poly = NTL::ZZX(large_value); // Wrong with large values
    ctxt.multByConstant(poly);

    NTL::ZZX dec;
    sk.Decrypt(dec, ctxt);
    /// I expect to get a poly [large_value * plain % q];
   /// but it gave a totally different poly.
    std::cout << dec << std::endl; /
}
```

**Comment by shaih** [comment]
My guess is that this is due to a decryption error. Try replacing `ctxt.multByConstant(poly)` by `ctxt.multByConstant(poly, size)`, where `size` (double) is the square L2-norm of the coefficient vectors of poly. Then call `ctxt.isCorrect()` to see if you should expect decryption errors for this large poly.

The thing to do is to make sure that poly is reduced modulo the plaintext space before multiplying.

**Comment by fionser** [comment]
@shaih Thanks for your response. I tried your suggestion. It shows "isCorrect = false`. 
So  can I use the `modSwitch` to reduce the noise ?

**Comment by shaih** [comment]
No, mod-switch will not work. You should (a) make sure that the 
plaintext poly is reduced modulo the plaintext space parameter (p^r), 
and (b) if this does not slove the problem then you must use more levels 
(i.e., call context.buildModChain with more levels).
