### ISSUE TITLE
"Decomposing" an Encrypted Array in Seperate Ciphertexts

### ISSUE THREAD

**Issue by emeka142** [shaih/HElib#182]
Please is it possible to "decompose elements" of an encrypted array ciphertext into separate ciphertexts for further computation. 
Alternatively, can someone compute on specific elements of an encrypted array ciphertext?

The same question goes for packing  into coefficients of ciphertext polynomials.

Thanks.

**Comment by fionser** [comment]
What do you mean by `decomposition` ? Any example ?

**Comment by emeka142** [comment]
So I have encrypted and added two sets of vectors with 16 elements in each, using encrypted array. 
Now I want to multiply some elements of the encrypted array without decrypting it first. 
So essentially I want to compute on individual elements of an encrypted array.
Is this possible? 
Thank you.

**Comment by ssmiler** [comment]
You can permute elements around the slots. So, move both elements you want
to multiply to the same slot position and perform the multiplication.

Le 16 déc. 2017 8:58 AM, "emeka142" <notifications@github.com> a écrit :

So I have encrypted and added two sets of vectors with 16 elements in each,
using encrypted array.
Now I want to multiply some elements of the encrypted array without
decrypting it first.
So essentially I want to compute on individual elements of an encrypted
array.
Is this possible?
Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shaih/HElib/issues/182#issuecomment-352168201>, or mute
the thread

**Comment by emeka142** [comment]
Thanks for you feedback. 
So I have performed a summation of  two encrypted arrays and I get an encrypted array as the result.

Now I want to multiply some elements in that encrypted array ( the summation ) with each other.  Ideally what I would want is a way to "decompose" or "split" the elements of that array into separate ciphertexts.

I guess I could create copy's of the encrypted array ciphertext (Summation), and use permutations to multiply them but I wanted to know if there is an easier way to do it.

I hope my example is clear enough.

**Comment by ssmiler** [comment]
Try to look how total sum method is done. I suppose you'll need only a log
number of multiplications.

**Comment by emeka142** [comment]
I probably did not explain the computation very well. Below is a brief summary

First array:  **x={1,2,3,4,5,}**
Second:     **y = {1,2,3,4,5}**
Summation of X and y,    **z={2,4,6,8,10}**
**Final Result = 2*4*6*8*10**  (Multiplication of elements of z)
This is the computation I want to perform by using encrypted array to encrypt x and y. I don't think the total sum method will be useful in this case. 

Thanks for your feedback

**Comment by sergiu-carpov** [comment]
Suppose you a ciphertext which encrypts 4 values: {0,1,2,3} (x+y in your case). You need to multiply values from every slot together.
Firstly you multiply the ciphertext and the ciphertext permuted by 2: {0,1,2,3} * {2,3,0,1} = {0.2,1.3,2.0,3.1}. Permuting by 1 the obtained ciphertext you have: {0.2,1.3,2.0,3.1} * {1.3,2.0,3.1,0.2} = {0.2.1.3,...}.
The result you need is in the first slot and you did only a log(4)=2 number of multiplications.
I suppose the total sum function in Helib does the same except that addition is used instead of multiplication.
Hope it helps.

**Comment by ssmiler** [comment]
Suppose you a ciphertext which encrypts 4 values: {0,1,2,3} (x+y in your case). You need to multiply values from every slot together.
Firstly you multiply the ciphertext and the ciphertext permuted by 2: {0,1,2,3} * {2,3,0,1} = {0.2,1.3,2.0,3.1}. Permuting by 1 the obtained ciphertext you have: {0.2,1.3,2.0,3.1} * {1.3,2.0,3.1,0.2} = {0.2.1.3,...}.
The result you need is in the first slot and you did only a log(4)=2 number of multiplications.
I suppose the total sum function in Helib does the same except that addition is used instead of multiplication.
Hope it helps.

**Comment by emeka142** [comment]
Thanks it works. 
I get this error after 4 shifts.

`myPpgp_x: Ctxt.cpp:303: void Ctxt::reLinearize(long int): Assertion `W.toKeyID>=0' failed.
Aborted (core dumped)
`
What parameters could to allow more shifts on encrypted array.

**Comment by fionser** [comment]
Did you call `addSome1DMatrices` when you create secret key?

**Comment by emeka142** [comment]
Yes indeed. And these are the parameters I have selected. 
`    long m=0, p=257, r=2;  long L=18; long c=3;  long w=64; long d=1; long security = 120;`

**Comment by fionser** [comment]
The assert fails, because the necessary key-switch matrix is not generated.
These key-switch matrices depend on the circuit you are going to evaluate.
So, the dummy method is to try `addAllMatrices` and check whether you get the correct result.
Then to figure out what matrices are necessary, and only generate them.

**Comment by fionser** [comment]
@emeka142 And use `multiplyBy` and not use the overloaded operator `*=` when you do the multiplication

**Comment by shaih** [comment]
addSome1DMatrices should work. But you do need to call multiplyBy rather than operator*=

**Comment by emeka142** [comment]
It works. Thank you
