### ISSUE TITLE
How to use operator== and operator>>=  In class Ctxt

### ISSUE THREAD

**Issue by KinoluKaslana** [shaih/HElib#200]
I've tried this tow functions in order to compare 0(been encrypted by same parameters） and >>=1 but is all wrong,== always return true >>=1 always return itself.

**Comment by fionser** [comment]
* You mean the `operator==` and `operator>>=` in Ctxt class ?
* If so, the `==` operators just compare whether the two ciphertexts are the same in the binary level.
* the `>>=` does not mean `greater or equals than`. This is a short cut for `automorphism` operation.

**Comment by KinoluKaslana** [comment]
@fionser OKay I'm greenhand and don't know a lot about homomorphic encryption,I'm wondering is there any way to any ciphertexts divide 2(ciphertexts)(I've done this by using operator-=)but I have to compare the dividend with 1(ciphertexts) and 0(ciphertexts) to stop the loop。 Could you please give me some advice?

**Comment by ssmiler** [comment]
You cannot have a loop stop condition depending on encrypted data,
otherwise you're leaking the plain value of the ciphertext you want to
compare to zero. You can have a loop with a fixed number of iterations and
obliviously update your variables.

Le mar. 24 avr. 2018 à 08:53, KinoluKaslana <notifications@github.com> a
écrit :

**Comment by KinoluKaslana** [comment]
@ssmiler Thank you for your advice but it is not suitable for me in order to have a loop with a fixed number is not suitable for any number,maybe I have to change aother mind.
