### ISSUE TITLE
Is it possible to do a 'greater than' comparison on two ciphertexts?

### ISSUE THREAD

**Issue by antoniosv** [shaih/HElib#45]
Apologies if this is not the proper place to ask such question.

Looking at the API, I found this function in NumbTh.h
```
long 	argmax (vector< long > &v, bool(*moreThan)(long, long))
```
 	A variant with a specialized comparison function (*moreThan)(a,b) returns the comparison a>b. 

I wish to know if the value of ciphertext a is greater than ciphertext b. Would I have to implement such a function? And if so, could I have any hints?

**Comment by shaih** [comment]
(a) You cannot expect to use homomorphic computation to get the result (a>b) in the clear, this will violate security.
(b) You can compute an encryption of the bit which is 1 if a>b and 0 otherwise. The procedure that you use for that depends on your plaintext space. For example:

+ If a,b are integers modulo some prime p, then you can compute c=a-b, and then evaluate a mod-p-polynomial on c that evaluates to 1 on all the values 1,2,...,p/2 and evaluates to 0 on all the points 0,-1,-2,...,-p/2.
+ If you have encryption of the bits in the binary representation of a,b, then you need to implement a Boolean circuit that computes the comparison output from the input bits.

**Comment by antoniosv** [comment]
After much thought, I realized it would violate security. I'll take into account your (b) suggestion for the project I'm working on. 
Thank you. :)

**Comment by lepro09** [comment]
@shaih  you said above "(b) You can compute an encryption of the bit which is 1 if a>b and 0 otherwise. The procedure that you use for that depends on your plaintext space."
i try : `ct1 *= ct2;
 ct1 += ct2;
` but it doesn't work.  How will you do it?
Thank. :)

**Comment by lastmjs** [comment]
> If a,b are integers modulo some prime p, then you can compute c=a-b, and then evaluate a mod-p-polynomial on c that evaluates to 1 on all the values 1,2,...,p/2 and evaluates to 0 on all the points 0,-1,-2,...,-p/2.

Do you have an example of one of these `mod-p-polynomials`? How would I go about finding one that is appropriate?
