### ISSUE TITLE
Proper parameters for key-switch

### ISSUE THREAD

**Issue by fionser** [shaih/HElib#46]
I am sorry I have to ask this question here. 
I got "W.toKeyID >=0" assertion failed but I have set up add1DMatrices(). 
Are there other reasons it happen?

**Comment by shaih** [comment]
My guess is that you were using the low-level c1 *= c2 instead of the high-level c1.multiplyBy(c2), the former does not do key-switching to after a few of these operations you will produce a ciphertext for which there are no key-switching matrices. Similar phenomena will happen when you use the low-level c.automorph(k) or c <<= k instead of the higher-level  c.smartAutomorph(k).

If this is not the case then please send a short code fragment that demonstrate the problem.

**Comment by fionser** [comment]
Yes. I had figure that out! Thank you very much!
