### ISSUE TITLE
Assertion `empty(s1 & map.getIndexSet())' failed.

### ISSUE THREAD

**Issue by alphacristi** [shaih/HElib#50]
When i am trying to multiply and add some ciphertexts i get this error :

 DoubleCRT.cpp:269: double DoubleCRT::addPrimesAndScale(const IndexSet&): Assertion `empty(s1 & map.getIndexSet())' failed.

Anyone knows what could be the problem ?
Thank you.

**Comment by TomMD** [comment]
These sorts of problems are easier to debug when you post your actual code.  Also, if you think the issue is your own and not a library bug the the issue tracker is not the best solution - consider using a programmer site such as stackoverflow.

All that said, are you using `*=` when you should probably be using `multiplyBy`?

**Comment by alphacristi** [comment]
I think that's the problem, using *= instead of multiplyBy.
Thanks.
