### ISSUE TITLE
Problem with NTL 9.3.x?

### ISSUE THREAD

**Issue by t-ghost** [shaih/HElib#65]
Hi!

After doing a system update, I stumbled upon a problem in the use of HElib together with NTL version 9.3.0.2. The error I get, says:
"findPrimitiveRoot : internal error(1)"

It seems to occur in the very basic setup of an encryption scheme (where exactly I don't know...), but it disappears when downgrading to the last version of NTL (9.2.01 on my Manjaro Linux system). It sounds like this is an error from within NTL, not from HElib (not sure!).

Maybe this note will be of help to others when running into the same problem.

Best regards!

**Comment by victorshoup** [comment]
Hi...thanks for your feedback!
I just tested it on my machine..with latest helib and NTLv9.3.
I did not get any errors on "make check".

After you updated NTL, did you also do a "make clean" in helib and rebuild?
I often get random errors in helib when I forget to do that.

If that is not the problem, then it is indeed very strange: the changes between
NTL v9.2 and 9.3 are very minor, an should (in theory) have no impact on helib.

-Victor

**Comment by t-ghost** [comment]
Hi!

To be honest, I did not try to run "make check" afterwards, but I did run
"make clean", so there should not be anything left from previous
compilations. In my code I have an object which basically holds the
internal basic parameters of the encryption (like m,p,r,  and so on) and it
does not get more complicated than in the Test_***.cpp examples. The error
occurs already when I try to initialize that object, which only sets those
basic parameters....

I will have another look at the error (and run 'make check') and report
back. It would be great if I could use 9.3 without problems.

Best,
Thomas

**Comment by t-ghost** [comment]
Oh, you are completely right!
I did rebuild my project (which has its own makefile) but not helib itself
after updateing NTL. That seems to have caused the problem...
Thanks for the reminder!

(Problem Solved!)

Best,
Thomas

**Comment by victorshoup** [comment]
Since this has been a recurring problem, it would be nice if there were
a simple, automatic way to detect such things, so that compiling or linking
would fail somehow.

I guess we could put into one of the cpp helib files the following:
like for building a context, something like:

  void VersionCheck_## ... preprocessor magic ... () { }

Here, ... preprocessor magic ... is some preprocessor magic
that will create a token out of NTL's version numbers.
These have parentheses around them, but I think there is a preprocessor hack
to get rid of them.

Anyway, assuming that works, then we do something like this...
we take something simple but fundamental, like the destructor for
FHEContext, make it "inline", and then add:

  void VersionCheck_## ... preprocessor magic ... ();
  VersionCheck_## ... preprocessor magic ... ();

Hopefully, this would cause the linker to fail if there is a version mismatch...

**Comment by t-ghost** [comment]
Something like this would really be great! Especially when you are coding
in the details of your project, you tend to forget about such things like
repcompiling helib after an update (like I did).
I think, at the most simple way it might even be enough to just memorize
NTLs version number somewhere when compiling is done and compare it with
the current version number while helib runs. (might be essentially the same
approach like you already mentioned)

Concerning the parentheses, I think, they might be no problem. If you take
it as a string and then just do string comparison, the parentheses will not
matter, but the chars (= numbers) will change, and the strings will not be
equal anymore (it's a rather crude approach, however, and yours sounds
neater in code)

**Comment by t-ghost** [comment]
(original problem solved by recompiling helib after ntl update)
