### ISSUE TITLE
Reading public key and Ctxt from file / string input

### ISSUE THREAD

**Issue by t-ghost** [shaih/HElib#77]
I have two related questions about reading the public key and Ctxts from text(string or file content).

While I was able to save and read the secret key in a file by using the stream operators (<<, >>) I couldn't do so with the public key. The problem there is that I am not sure what type to use. For the secret key I did the following:

fstream keyFile(fileName, fstream::in);
//construct key with a preexistent context...
FHESecKey secretKey(tmpCon);
//...but overwrite it
keyFile >> secretKey;
keyFile.close();

Previously, I wrote the secret key to the file by <<.
Is there a way to do this for the public key? Or did I get something wrong in the code above?

My second question is related in context to the stream operator:

As far as I know, I can read a Ctxt like so:

stringstream cs(ciphertext);
Ctxt ct(publicKey);
cs >> ct;

Here I am using the stringstream as a means to transform the string 'ciphertext' to a stream so I can make use of >>. Is there an easier way to do this? Do I really need to construct a Ctxt with the public key?

Thanks in advance,
Regards

**Comment by shaih** [comment]
I think that casting a secret key to FHEPubKey and then using >> to 
output it should work. On the receiving end you can get it back via

   FHEPubKey pk(context);  // context was read before
   cin >> pk;              // or any other stream instead of cin

There is some code (commented out) at the bottom of the file Test_IO.cpp 
that does this, and as far as I remember this still works.

Also, no need for stringstream, you should be able to use any i/o stream.

-- Shai

**Comment by t-ghost** [comment]
Thanks! This is exaclty what I was looking for (must have overlooked it in the examples...)
I will try this in my code.
