### ISSUE TITLE
Binary carry problem in an addition operation

### ISSUE THREAD

**Issue by maycherish** [shaih/HElib#81]
I'm trying to encrypt two plaintexts which are integers. I have two ciphertexts c1 and c2 that I add between them with c1+=c2.,however  the two ciphertexts don't carry in an addition operation.
I wonder if someone has a piece of code to show me how to add between two ciphertexts and if possible with the bunch of variables used for the given code.

In advance, many thanks.

**Comment by shaih** [comment]
If the numbers are small, you can consider setting the plaintext-space to something large enough so that you can directly add them as integers. (For example, setting p=17 allow you do directly get arithmetic modulo 17. So you can do 3+10 and you would get 13, but 11+12 will return 23 mod 17=6.)  The performance deteriorates with p, whoever, so this option is only reasonable for p upto 100 or so.

If you want to implement homomorphic integer arithmetic above 100 or so, you would need to implement the carry bits yourself (using multiplies). For example you can set p=2 and work with binary representation. Then to add 3+4 you would have 011 representing 3 and 100 representing 4, and you would have to compute the carry bits yourself (i.e., _carry_i = x_i * y_i + x_i * carry_{i-1} + y_i * carry_{i-1} mod 2_).

**Comment by umikachen** [comment]
Actually I have met the same problem, I wrote a binary arithmetic(addition/subtraction/multiplication) library based on HElib. The implementation is like what @shaih said. (set p=2, and do carryin bits by myself).  
https://github.com/umikachen/HEBinCalc

But here I have a performance issue. Since one bit addition costs 3 homomorphic multiplications and 4 homomorphic addtions, and this should times N when you want to calculate a N-bit integer, I have to set a relative big L(level) in HElib. This will cause a large m by function FindM. But in fact I only use the first slot of every ciphertext to store one bit, all other slots in a Ctxt object are wasted. 

So I hope I can find a way to use as few slots per Ctxt as possible, then I tried to set a small m(m=3) in HElib. The result is correct and the calculation is fast, but I know it is [not secure enough](https://github.com/umikachen/HEBinCalc#an-ideal-case-but-not-safe---as-few-slots-per-ctxt-as-possible). Is it possible to use the advantages of SIMD in this scenario, or is it possible to modify HElib and make it based on LWE(then I have a large integer but not a polynomial to represent a bit, and slots is not an issue anymore)?  Do you have any suggestions? Thanks in advance.

**Comment by ssmiler** [comment]
Take a look at this article https://eprint.iacr.org/2009/411.pdf On page 6 you have an adder with only one multiplication per bit, although as in your implementation the multiplicative depth is N. You can do better with carry lookahead adders, namely with log_2(N).
From what I have seen in literature in this paper https://eprint.iacr.org/2011/405.pdf (see section 4.1) the authors encode an N bit number as a polynomial of degree N, which in turn is encrypted in a ciphertext. By adding two such ciphertexts you perform an addition... but without carry propagation.
In any case I think it's impossible to perform an addition of N bit numbers with multiplicative depth less than log_2(N).

**Comment by umikachen** [comment]
Thank you so much for your reply! The first paper is really helpful. By a slight change to an equivalent logical expression, I can gain more than 100% speedup.(I have updated my code based on this trick, although still slow) 
I am recently considering about the carry lookahead adders(CLA), and have found that CLA cannot get any speedup than the ordinary adder unless I use parallel computing. I know that the new version of NTL is thread safe so this seems a possible solution. But does HElib support the concurrent computation(addition and multiplication) of ciphertext?

**Comment by ssmiler** [comment]
I think that CLA will run faster using FHE as the multiplicative depth will be log2(N) instead of N. Even if more AND gates are executed, gate execution time decreases with the multiplicative depth.
You can choose a multiplicative depth (number of levels parameter) when generating params for HElib.

**Comment by umikachen** [comment]
Well, I am little confused. Please correct me if I am wrong.
When you say "log2(N)" do you mean the hardware(gates) implementation? I think the gates in the same level work simultaneously but not one by one. But when we write code to simulate this process, all the gates work in serial, not in parallel. This makes the soft implementation much slower.
Since I have implemented a 16-bit CLA adder base on this tutorial (It's a 64-bit implementation, so step 3 and 4 are omited to get a 16-bit version):
[http://rpi-csci-2500-2016-spring.github.io/slides/pdf/cla.pdf](http://rpi-csci-2500-2016-spring.github.io/slides/pdf/cla.pdf )
I don't think this can be done with L=log2(16)=4 in any way. Actually, at least I have to set L=17 to get the correct answer. 
Can you show me some reference about log2(N) stuff? 
Thank you.

**Comment by umikachen** [comment]
I realized my mistake and I now know what you mean. For example, if I compute a*b*c*d, I can reduce multiplicative depth by doing a*b and c*d separately, then combine them together(in this way multiplicative depth is 2 but not 3). I can do some modification in my code and verify this. Thank you.

**Comment by ssmiler** [comment]
Yes, this is what I meant ;)

**Comment by shaih** [comment]
Binary addition, multiplication, etc. were added to HElib late last year.
