### ISSUE TITLE
Comparison on ciphertexts

### ISSUE THREAD

**Issue by lepro09** [shaih/HElib#82]
I' m trying to make comparisons on ciphertexts.
Given two ciphertext c1 and c2 of two values p1=p2 =1, instruction c1==c2 or c1.equalsTo(c2) always give false.
Do you have any idea how i can solve this?

Is it possible to do a greater than comparison in the form (c1 < c2) on two ciphertexts?

**Comment by ssmiler** [comment]
You cannot compare two ciphertexts and obtain the result as cleartext, otherwise the scheme will not be secure.

What you can do is to obtain the result of comparison encrypted in a new ciphertext. For example for modulo 2 plaintext space, adding two ciphertext will result in "!=" operator. Add "1" to it in order to obtain "==" operator.

**Comment by mominbuet** [comment]
Is there any OPE schemes based on lattice available? (Just a random question ;) )

**Comment by lepro09** [comment]
@ssmiler Thank for your advice.

**Comment by TomMD** [comment]
@mominbuet Github issue's aren't really for arbitrary questions.  I suggest you post your question to an appropriate internet forum such as http://crypto.stackexchange.com

@lepro09 If your issue is addressed then it helps the maintainer if you close it (only you as the original author or a maintainer can close the issue).

**Comment by lepro09** [comment]
@ssmiler I try it. it seems to work but I still need to decrypt the result and check. Does it exist any other way to compare without decryption?

**Comment by ssmiler** [comment]
@lepro09 It's a ciphertext, you must decrypt it in order to see the result ;) 
Why do you need comparison without decryption?

**Comment by lepro09** [comment]
@ssmiler  i just need to compare if the two ciphertexts encrypt the same plaintext.

**Comment by ssmiler** [comment]
@lepro09 Only decryption then in HE context.

**Comment by lepro09** [comment]
@ssmiler Thanks a lot!!
