### ISSUE TITLE
Homomorphic Evaluation of the AES circuit on one block

### ISSUE THREAD

**Issue by axelmma** [shaih/HElib#89]
I have a couple of questions concerning the Homomorphic Evaluation of the AES circuit.
It is clear to me that the AES byte-sliced implementation provided here can process upto 120 blocks in an evaluation. 
But I was wondering if Helib allows us to process only 1 block ?
Or if it is necessary to process 120 blocks at the same time ? 

Because so far, I haven't been able to choose the exact number of slots that I want to compute on.

Thanks.

**Comment by ssmiler** [comment]
The number of blocks depends on the parameters you use to obtain a secure FHE, more precisely the degree of the cyclotomic polynomial which influences the number of slots (ie number of AES blocks you treat in parallel). I don't think you'll be able to chose smaller degree polynomial for the multiplicative depth required by AES. Finally, you can use only one block and ignore the others.

A solution will be to reorganize the AES computation (using slot permutation for example) in order to pack the AES state in a single ciphertext. But this will not be an obvious think to do :)

**Comment by axelmma** [comment]
Indeed, it is probably better to leave it that way ! :-)
 
Thanks again for your answer !
